#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;
use Carp;

$| = 1;


###########################
#####     SETTNGS     #####
###########################

# change the variables below 
# set here the path to your wallpapers
# and the seconds between every wallpaper
# 
# $ENV{'HOME'} represents your "/home/<USER>/" directory
#
# you also can call the script with following arguments. 
# This overwrites the settings in the script
# 
# $ backslide <image_directory> <seconds>;

my $directory = "$ENV{'HOME'}/Pictures/.wallpaper/"; # path to your wallpaper folder
my $sleep = 30; # seconds to wait for changing your wallpaper again

$directory =~ s/\/$//;


my @files;
my $picture;
my $backnum;
my $backdrop;
my $last;

if($ARGV[0]) {
    $directory = $ARGV[0];
}
if($ARGV[1]) {
    $sleep = $ARGV[1];
}

while(1) {
    sleep(int($sleep/2) + int(rand($sleep))); # wait  <sec> +- 50%
    
    undef(@files);

    opendir (DIR, $directory) or die $!;
    @files = readdir(DIR);
    closedir(DIR);
    
    @files = grep(m/.\.(jpg|gif|png|jpeg)$/i, @files);
    @files = grep(!-d $directory.'/'.$_, @files);
    
    if(@files <= 1) { # dont do anything when there is only one picture
        sleep($sleep);
        redo;
    }
    
    
    if(!$last) {
        $picture = $files[int(rand(scalar(@files)))];
    } else {
        while($last eq $picture) {
             $picture = $files[rand(scalar(@files))];
        }
    }
    
    $last = $picture; #finally memorize the last backdrop
    
    $backdrop = $directory.'/'.$picture;
    system("gsettings set org.gnome.desktop.background picture-uri 'file://$backdrop'"); # set wallpaper
} 
